spring.application.name=ptip

server.port=443
#server.http.port=80
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:ssl/keystore.p12
server.ssl.key-store-password=ptip@spring
server.ssl.key-alias=ptip.p-e.kr

# HTTP ? HTTPS ?? ????
#server.http.redirect-to-https=true

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://ptip-db-server.mysql.database.azure.com:3306/award?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=ptip_admin
spring.datasource.password=ptu@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver